/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/files/image-uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create image upload sessions
         * @description First step of publication creation. Send metadata of the final files after any client-side editing. The response contains one short-lived presigned POST session per image. Match each session to the local file by clientFileId, copy every returned field into FormData, append the file last and POST the form directly to the returned Object Storage URL. After the selected uploads succeed, call the image-uploads/complete endpoint with their session IDs.
         */
        post: operations["initiateImageUploads"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/image-uploads/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm direct image uploads
         * @description Call this endpoint after Object Storage has successfully accepted every selected multipart/form-data request. Files verifies ownership and performs HeadObject for each ID without downloading the object. The stored size and Content-Type must exactly match the metadata supplied when the session was created. The current implementation does not inspect magic bytes or decode the image contents. If one object is missing or mismatched, the whole submitted set becomes REJECTED. Repeating a request for an already COMPLETED set succeeds, making confirmation idempotent.
         */
        post: operations["completeImageUploads"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/images/{fileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Redirect to a public image
         * @description Resolves a completed, non-deleted file by its ID and redirects the client to its public Object Storage URL. The gateway does not proxy the image bytes. Browsers follow the redirect and download the image directly from Object Storage.
         */
        get: operations["getPublicFileUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a post with completed image uploads
         * @description Final step of publication creation. Supply the IDs previously confirmed through files/image-uploads/complete in their display order. Posts asks Files over gRPC to reserve images that exist, belong to the authenticated author, are not soft-deleted and have status COMPLETED. The post and its ordered image relations are then created atomically, after which the reservation is marked as attached.
         */
        post: operations["createPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{postId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update a post
         * @description Updates the description of a post owned by the authenticated user.
         */
        put: operations["updatePost"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userId}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an author's posts using cursor pagination */
        get: operations["getAuthorPosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/testing/all-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete all data from the microservice databases */
        delete: operations["deleteAllData"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/registration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a user and send an email confirmation link */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/registration/confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm registration using the code from the email link */
        post: operations["confirmRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/registration/resend-confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a new registration confirmation link */
        post: operations["resendRegistrationConfirmation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in
         * @description Returns an access token and stores the refresh token in an httpOnly cookie.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the refresh token
         * @description Returns a new access token and replaces the refresh token cookie.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password reset email
         * @description Accepts the request without revealing whether the email exists. If a reset email was sent recently, the backend keeps a 1 minute cooldown and does not send another email during that window. The client should disable the resend button for 1 minute after submitting this request.
         */
        post: operations["passwordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a new password using a password reset token */
        post: operations["confirmPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out from the current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Start Google OIDC authentication
         * @description Starts the Google OpenID Connect authorization-code flow. This endpoint is intended for browser navigation, not an AJAX request.
         *
         *     The gateway creates short-lived, HttpOnly transaction cookies for state, nonce and the PKCE verifier, then redirects the browser to Google.
         */
        get: operations["googleAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Complete Google OIDC authentication
         * @description Callback invoked by Google after authorization. It is intended for browser navigation and always redirects to the frontend.
         *
         *     The gateway validates state, nonce and PKCE, clears the one-time transaction cookies and creates an application session.
         *     On success, the refresh token is stored in a secure HttpOnly cookie. On failure, the frontend receives only a public OAuth error code.
         */
        get: operations["googleAuthCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Start GitHub OAuth authentication
         * @description Starts the GitHub OAuth authorization flow. This endpoint is intended for browser navigation, not an AJAX request. The response redirects the browser to GitHub, where the user grants access to the application.
         */
        get: operations["githubAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/github/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Complete GitHub OAuth authentication
         * @description Callback invoked by GitHub after authorization. It is intended for browser navigation and always redirects to the frontend.
         *
         *     On success, the gateway stores the refresh token in a secure httpOnly cookie and redirects to the frontend.
         *     If user action is required or authentication fails, the gateway redirects to the frontend login flow with a public OAuth error code.
         *     Tokens, the GitHub subject and internal exception messages are never included in the redirect URL.
         */
        get: operations["githubAuthRedirect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/security/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the active sessions of the current user */
        get: operations["getSessions"];
        put?: never;
        post?: never;
        /** Revoke all sessions except the current one */
        delete: operations["deleteOtherSessions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/security/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a selected session */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiErrorResponseDto: {
            /** @description HTTP status code. */
            statusCode: number;
            /** @description Stable machine-readable application error code. */
            code: string;
            /** @description Human-readable diagnostic message. */
            message: string;
        };
        ValidationErrorResponseDto: {
            /** @example 400 */
            statusCode: number;
            /**
             * @example [
             *       "email must be an email"
             *     ]
             */
            message: string[];
            /** @example Bad Request */
            error: string;
        };
        ImageUploadMetadataDto: {
            /**
             * Format: uuid
             * @description Client-generated correlation ID used to match the returned session to this local file.
             * @example 83d26252-a350-4e39-a78e-0bdf54d2341d
             */
            clientFileId: string;
            /**
             * @description Original filename kept as file metadata; it is not used as the Object Storage key.
             * @example photo.jpg
             */
            originalFilename: string;
            /**
             * @description MIME type of the exact file that will be uploaded. Only JPEG and PNG are supported.
             * @example image/jpeg
             * @enum {string}
             */
            contentType: "image/jpeg" | "image/png";
            /**
             * @description Exact size of the final file in bytes. The presigned POST policy and completion check require this exact value.
             * @example 1048576
             */
            size: number;
        };
        InitiateImageUploadsDto: {
            /** @description Metadata for 1–10 final images after any client-side crop or filter processing. */
            images: components["schemas"]["ImageUploadMetadataDto"][];
        };
        ImageUploadSessionDto: {
            /**
             * Format: uuid
             * @description Server-generated upload ID used for confirmation and later as the post image ID.
             * @example 83d26252-a350-4e39-a78e-0bdf54d2341d
             */
            id: string;
            /**
             * Format: uuid
             * @description The client correlation ID from the matching request item.
             * @example 2b610f18-cb6c-4c4a-aed1-cf8f0bff3b55
             */
            clientFileId: string;
            /**
             * @description Yandex Object Storage URL to which the multipart/form-data POST must be sent.
             * @example https://storage.yandexcloud.net/images-bucket
             */
            url: string;
            /**
             * @description Opaque signed form fields. Append every entry unchanged to FormData, then append the file field last.
             * @example {
             *       "key": "users/42/images/83d26252-a350-4e39-a78e-0bdf54d2341d",
             *       "Content-Type": "image/jpeg",
             *       "X-Amz-Algorithm": "AWS4-HMAC-SHA256",
             *       "X-Amz-Credential": "access-key/20260806/ru-central1/s3/aws4_request",
             *       "X-Amz-Date": "20260806T120000Z",
             *       "Policy": "base64-encoded-policy",
             *       "X-Amz-Signature": "hex-encoded-signature"
             *     }
             */
            fields: {
                [key: string]: string;
            };
        };
        InitiateImageUploadsResponseDto: {
            /** @description One presigned POST session for each requested image. */
            sessions: components["schemas"]["ImageUploadSessionDto"][];
        };
        CompleteImageUploadsDto: {
            /**
             * @description Session IDs returned by image-uploads for objects that Object Storage has accepted successfully.
             * @example [
             *       "83d26252-a350-4e39-a78e-0bdf54d2341d"
             *     ]
             */
            uploadIds: string[];
        };
        CreatePostDto: {
            /**
             * @description Optional post description. An omitted value is stored as NULL; an empty string remains empty.
             * @example A new post
             */
            description?: string;
            /**
             * @description Completed image upload IDs in display order. Every image must belong to the authenticated author.
             * @example [
             *       "83d26252-a350-4e39-a78e-0bdf54d2341d"
             *     ]
             */
            imageIds: string[];
        };
        CreatePostResponseDto: {
            /**
             * @description Identifier of the newly created post.
             * @example 10
             */
            id: number;
        };
        UpdatePostDto: {
            /** @example Some description */
            description: string;
        };
        Object: Record<string, never>;
        AuthorPostImageDto: {
            /**
             * Format: uuid
             * @description Image file identifier.
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            fileId: string;
            /**
             * @description Zero-based image position inside the post.
             * @example 0
             */
            position: number;
            /**
             * Format: uri
             * @description Absolute API Gateway URL that redirects to the public image.
             * @example https://api.remark-gram.com/api/v1/files/images/550e8400-e29b-41d4-a716-446655440000
             */
            url: string;
        };
        AuthorPostDto: {
            /**
             * @description Post identifier.
             * @example 42
             */
            id: number;
            /**
             * @description Author identifier.
             * @example 7
             */
            authorId: number;
            /**
             * @description Post description, or null when the post has no description.
             * @example My first post
             */
            description: Record<string, never> | null;
            /**
             * Format: date-time
             * @description Post creation date in ISO 8601 format.
             * @example 2026-08-11T11:00:00.000Z
             */
            createdAt: string;
            /** @description Post images ordered by position. */
            images: components["schemas"]["AuthorPostImageDto"][];
        };
        GetAuthorPostsDto: {
            /** @description Posts from the requested page. */
            items: components["schemas"]["AuthorPostDto"][];
            /**
             * @description Whether another page is available.
             * @example true
             */
            hasMore: boolean;
            /**
             * @description Opaque cursor for the next page, or null when this is the last page.
             * @example eyJpZCI6NDIsImNyZWF0ZWRBdCI6IjIwMjYtMDgtMTFUMTE6MDA6MDAuMDAwWiJ9
             */
            nextCursor: Record<string, never> | null;
        };
        RegistrationDto: {
            /** @example user_123 */
            username: string;
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /**
             * @description Must contain at least one digit, one uppercase letter and one lowercase letter.
             * @example Password1!
             */
            password: string;
        };
        ConfirmRegistrationDto: {
            /** @example 34c78352-97d1-4f2f-a0a2-41e28365d926 */
            code: string;
        };
        ResendRegistrationConfirmationDto: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
        };
        LoginDto: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /**
             * Format: password
             * @example Password1!
             */
            password: string;
        };
        AccessTokenResponseDto: {
            /** @description JWT access token. */
            accessToken: string;
        };
        PasswordResetDto: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example recaptcha-reset-token */
            recaptchaToken: string;
        };
        PasswordResetResponse: {
            /** @example If this email exists, password reset instructions were sent. */
            message: string;
        };
        ConfirmPasswordResetDto: {
            /**
             * @description Token from the password reset email. Invalid, expired, revoked or already used tokens return INVALID_PASSWORD_RESET_TOKEN.
             * @example password-reset-token
             */
            token: string;
            /**
             * @description Must contain at least one digit, one uppercase letter and one lowercase letter.
             * @example NewPassword1!
             */
            newPassword: string;
        };
        ConfirmPasswordResetResponseDto: {
            /** @example Password has been changed successfully. */
            message: string;
        };
        SessionResponseDto: {
            /**
             * Format: uuid
             * @example e3637e61-194b-4f79-9676-e59a20bb7c42
             */
            sessionId: string;
            /** @example Mozilla/5.0 */
            deviceName: string;
            /** @example 127.0.0.1 */
            ip: string;
            /**
             * Format: date-time
             * @example 2026-07-07T12:00:00.000Z
             */
            lastActiveAt: string;
            /** @example true */
            isCurrent: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaApiErrorResponseDto = components['schemas']['ApiErrorResponseDto'];
export type SchemaValidationErrorResponseDto = components['schemas']['ValidationErrorResponseDto'];
export type SchemaImageUploadMetadataDto = components['schemas']['ImageUploadMetadataDto'];
export type SchemaInitiateImageUploadsDto = components['schemas']['InitiateImageUploadsDto'];
export type SchemaImageUploadSessionDto = components['schemas']['ImageUploadSessionDto'];
export type SchemaInitiateImageUploadsResponseDto = components['schemas']['InitiateImageUploadsResponseDto'];
export type SchemaCompleteImageUploadsDto = components['schemas']['CompleteImageUploadsDto'];
export type SchemaCreatePostDto = components['schemas']['CreatePostDto'];
export type SchemaCreatePostResponseDto = components['schemas']['CreatePostResponseDto'];
export type SchemaUpdatePostDto = components['schemas']['UpdatePostDto'];
export type SchemaObject = components['schemas']['Object'];
export type SchemaAuthorPostImageDto = components['schemas']['AuthorPostImageDto'];
export type SchemaAuthorPostDto = components['schemas']['AuthorPostDto'];
export type SchemaGetAuthorPostsDto = components['schemas']['GetAuthorPostsDto'];
export type SchemaRegistrationDto = components['schemas']['RegistrationDto'];
export type SchemaConfirmRegistrationDto = components['schemas']['ConfirmRegistrationDto'];
export type SchemaResendRegistrationConfirmationDto = components['schemas']['ResendRegistrationConfirmationDto'];
export type SchemaLoginDto = components['schemas']['LoginDto'];
export type SchemaAccessTokenResponseDto = components['schemas']['AccessTokenResponseDto'];
export type SchemaPasswordResetDto = components['schemas']['PasswordResetDto'];
export type SchemaPasswordResetResponse = components['schemas']['PasswordResetResponse'];
export type SchemaConfirmPasswordResetDto = components['schemas']['ConfirmPasswordResetDto'];
export type SchemaConfirmPasswordResetResponseDto = components['schemas']['ConfirmPasswordResetResponseDto'];
export type SchemaSessionResponseDto = components['schemas']['SessionResponseDto'];
export type $defs = Record<string, never>;
export interface operations {
    initiateImageUploads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Metadata must describe the exact Blob or File that will be uploaded to Object Storage. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitiateImageUploadsDto"];
            };
        };
        responses: {
            /** @description Short-lived presigned POST sessions were created and saved as PENDING. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InitiateImageUploadsResponseDto"];
                };
            };
            /** @description The request shape is invalid or an upload invariant is violated: image count, size, content type or unique clientFileId. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"] | components["schemas"]["ValidationErrorResponseDto"];
                };
            };
            /** @description The access token is missing, invalid or expired. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 401 */
                        statusCode: number;
                        /** @example Invalid access token */
                        message: string;
                        /** @example Unauthorized */
                        error: string;
                    };
                };
            };
            /** @description The files service or Object Storage returned an unexpected error. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description The files service is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    completeImageUploads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description IDs of successfully uploaded sessions. A subset of the originally created sessions may be confirmed. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteImageUploadsDto"];
            };
        };
        responses: {
            /** @description Every submitted upload is confirmed as COMPLETED. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request is malformed, contains duplicate IDs or contains fewer than 1 or more than 10 IDs. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"] | components["schemas"]["ValidationErrorResponseDto"];
                };
            };
            /** @description The access token is missing, invalid or expired. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 401 */
                        statusCode: number;
                        /** @example Invalid access token */
                        message: string;
                        /** @example Unauthorized */
                        error: string;
                    };
                };
            };
            /** @description At least one upload does not exist, belongs to another user or is soft-deleted. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description The upload statuses are incompatible or Object Storage metadata does not match. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description The files service or Object Storage returned an unexpected error. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description The files service is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    getPublicFileUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifier of the completed, non-deleted image file. */
                fileId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The client is redirected to the public Object Storage URL of the image. */
            302: {
                headers: {
                    /** @description Public URL of the image in Object Storage. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The fileId path parameter is not a UUID v4. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 400,
                     *       "message": [
                     *         "fileId must be a UUID"
                     *       ],
                     *       "error": "Bad Request"
                     *     }
                     */
                    "application/json": components["schemas"]["ValidationErrorResponseDto"];
                };
            };
            /** @description The access token is missing, invalid or expired. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 401 */
                        statusCode: number;
                        /** @example Invalid access token */
                        message: string;
                        /** @example Unauthorized */
                        error: string;
                    };
                };
            };
            /** @description Object Storage cannot provide a public URL for the file. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 403,
                     *       "code": "FILE_PUBLIC_ACCESS_DENIED",
                     *       "message": "File is not public"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description The file does not exist or is not available for public delivery. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 404,
                     *       "code": "FILE_NOT_FOUND",
                     *       "message": "File not found"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description The files service or Object Storage returned an unexpected error. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description The files service is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    createPost: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated UUID for one publication attempt. Reuse the same value only when retrying an identical request. The current API version accepts this header but does not yet enforce request-level idempotency. */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        /** @description Post description and completed image IDs in the desired display order. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePostDto"];
            };
        };
        responses: {
            /** @description The post and all ordered image relations were created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePostResponseDto"];
                };
            };
            /** @description The request shape is invalid or a post invariant is violated: description length, image count or unique image IDs. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"] | components["schemas"]["ValidationErrorResponseDto"];
                };
            };
            /** @description The access token is missing, invalid or expired. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 401 */
                        statusCode: number;
                        /** @example Invalid access token */
                        message: string;
                        /** @example Unauthorized */
                        error: string;
                    };
                };
            };
            /** @description At least one image does not exist, belongs to another user or is soft-deleted. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description At least one image cannot be reserved in its current state or is already attached to another post. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description The posts service or one of its dependencies returned an unexpected error. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Posts could not verify images because Files is unavailable or exceeded its deadline. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    updatePost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePostDto"];
            };
        };
        responses: {
            /** @description The post has been successfully updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The path parameter or request body is invalid, or the posts service rejected an invalid post ID, user ID, or description. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseDto"] | components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description The access token is missing, invalid or expired. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 401 */
                        statusCode: number;
                        /** @example Invalid access token */
                        message: string;
                        /** @example Unauthorized */
                        error: string;
                    };
                };
            };
            /** @description The authenticated user is not allowed to update this post. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description The post was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description The post was modified concurrently and could not be updated. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description The upstream service returned an unexpected error. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description The posts service is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    getAuthorPosts: {
        parameters: {
            query?: {
                /** @description Maximum number of posts returned in one page. */
                limit?: components["schemas"]["Object"];
                /** @description Opaque Base64 cursor returned as nextCursor by the previous page. */
                cursor?: string;
            };
            header?: never;
            path: {
                /** @description Numeric identifier of the author whose posts are requested. */
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested page of the author's posts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAuthorPostsDto"];
                };
            };
        };
    };
    deleteAllData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All microservice database data was deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The testing endpoint key is invalid. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The testing endpoint is disabled. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An upstream service returned an unexpected error. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A microservice is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrationDto"];
            };
        };
        responses: {
            /** @description The user was registered and the confirmation email was sent. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request body is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseDto"];
                };
            };
            /** @description The username or email is already reserved. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description The upstream service returned an unexpected error. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user-accounts service is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    confirmRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmRegistrationDto"];
            };
        };
        responses: {
            /** @description The email was confirmed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request body or confirmation code is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"] | components["schemas"]["ValidationErrorResponseDto"];
                };
            };
            /** @description The upstream service returned an unexpected error. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user-accounts service is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resendRegistrationConfirmation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendRegistrationConfirmationDto"];
            };
        };
        responses: {
            /** @description A new confirmation email was sent when resending was applicable. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The email is malformed or does not belong to a user. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"] | components["schemas"]["ValidationErrorResponseDto"];
                };
            };
            /** @description The email is already confirmed. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description The upstream service returned an unexpected error. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user-accounts service is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Authentication succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenResponseDto"];
                };
            };
            /** @description The request body is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseDto"];
                };
            };
            /** @description The email or password is incorrect. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description The email is not confirmed or the session is already active. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description The upstream service returned an unexpected error. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user-accounts service is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The token pair was rotated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenResponseDto"];
                };
            };
            /** @description The refresh token or its session is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description The upstream service returned an unexpected error. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user-accounts service is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    passwordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetDto"];
            };
        };
        responses: {
            /** @description The request was accepted. A reset email is sent only when the email belongs to a confirmed user and the 1 minute resend cooldown is not active. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordResetResponse"];
                };
            };
            /** @description The email is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseDto"];
                };
            };
            /** @description The upstream service returned an unexpected error. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user-accounts service is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    confirmPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Password reset confirmation payload. The token is taken from the password reset link sent by email. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmPasswordResetDto"];
            };
        };
        responses: {
            /** @description The password was changed and active sessions were revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmPasswordResetResponseDto"];
                };
            };
            /** @description The reset token or new password is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"] | components["schemas"]["ValidationErrorResponseDto"];
                };
            };
            /** @description The upstream service returned an unexpected error. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user-accounts service is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current session was revoked and the refresh cookie was cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The refresh token or its session is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description The upstream service returned an unexpected error. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user-accounts service is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    googleAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The browser is redirected to Google and receives the temporary OIDC transaction cookies. */
            302: {
                headers: {
                    /** @description Google authorization URL containing state, nonce and the S256 PKCE challenge. */
                    Location?: string;
                    /** @description Three short-lived HttpOnly cookies containing the OIDC state, nonce and PKCE verifier. Secure is enabled for an HTTPS callback. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The upstream service returned an unexpected error. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user-accounts service is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    googleAuthCallback: {
        parameters: {
            query?: {
                /** @description Temporary authorization code returned by Google after successful authorization. */
                code?: string;
                /** @description OIDC state returned by Google and compared with the browser transaction cookie. */
                state?: string;
                /** @description OAuth error returned by Google when authorization was not completed. */
                error?: string;
                /** @description Optional diagnostic description returned by Google. */
                error_description?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description OIDC processing finished and the browser is redirected to the frontend.
             *
             *     Success: the response clears the transaction cookies and sets the refreshToken cookie.
             *     Public error codes: EMAIL_REQUIRED, EMAIL_NOT_VERIFIED, EMAIL_CONFIRMATION_REQUIRED, IDENTITY_OWNER_NOT_FOUND, IDENTITY_LINKED_TO_ANOTHER_USER, PROVIDER_ALREADY_LINKED, IDENTITY_CONFLICT, ACCESS_DENIED, SERVICE_UNAVAILABLE or UNKNOWN_ERROR.
             */
            302: {
                headers: {
                    /** @description Frontend URL representing the OAuth result. */
                    Location?: string;
                    /** @description Always expires the state, nonce and PKCE cookies. After successful authentication it also stores refreshToken with HttpOnly, Secure and SameSite=Strict attributes. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The upstream service returned an unexpected error. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user-accounts service is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    githubAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The browser is redirected to the GitHub authorization page. */
            302: {
                headers: {
                    /** @description GitHub OAuth authorization URL. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The upstream service returned an unexpected error. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user-accounts service is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    githubAuthRedirect: {
        parameters: {
            query?: {
                /** @description Temporary authorization code returned by GitHub. */
                code?: string;
                /** @description OAuth error returned by GitHub when authorization was not completed. */
                error?: string;
                /** @description Optional diagnostic description returned by GitHub. */
                error_description?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description OAuth processing finished and the browser is redirected to the frontend.
             *
             *     Success: the response includes the refreshToken cookie.
             *     Public error codes: EMAIL_REQUIRED, EMAIL_NOT_VERIFIED, EMAIL_CONFIRMATION_REQUIRED, IDENTITY_OWNER_NOT_FOUND, IDENTITY_LINKED_TO_ANOTHER_USER, PROVIDER_ALREADY_LINKED, IDENTITY_CONFLICT, ACCESS_DENIED, SERVICE_UNAVAILABLE or UNKNOWN_ERROR.
             */
            302: {
                headers: {
                    /** @description Frontend URL representing the OAuth result. */
                    Location?: string;
                    /** @description Present only after successful authentication. Stores refreshToken with HttpOnly, Secure and SameSite=Strict attributes. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The upstream service returned an unexpected error. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user-accounts service is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active, unexpired and non-revoked refresh sessions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponseDto"][];
                };
            };
            /** @description The refresh token or its session is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The upstream service returned an unexpected error. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user-accounts service is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteOtherSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All other sessions were revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The refresh token or its session is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The upstream service returned an unexpected error. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user-accounts service is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session identifier. */
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The selected session was revoked. If the current session was selected, the refresh cookie was cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The refresh token or its session is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The session does not exist or does not belong to the current user. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description The upstream service returned an unexpected error. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user-accounts service is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
